name: 'Simple Pull Request GitHub Action'
description: 'Creates Pull Request after running specified command.'
branding:
  icon: 'arrow-up-circle'
  color: 'green'
inputs:
  command:
    description: Command to execute
    required: true
  token:
    description: GitHub Token to create a pull request
    required: true
  branch:
    description: Main branch name
    required: false
  path:
    description: Path to the directory where command will be executed
    required: false
runs:
  using: 'composite'
  steps:
    - run: pre-command.sh ${{ inputs.path }}
      shell: bash
    - run: command.sh ${{ inputs.command }} ${{ inputs.path }}?
      shell: bash
    - run: post-command.sh ${{ inputs.token }} ${{ inputs.branch }}? ${{ inputs.path }}?
      shell: bash
